# --- PURANA LOCAL DATABASE (BACKUP KE LIYE HIDE KIYA HAI) ---
 spring.datasource.url=jdbc:mysql://localhost:3306/mess_management
 spring.datasource.username=root
 spring.datasource.password=10lpa

# --- NAYA ONLINE DATABASE (AIVEN) ---
#spring.datasource.url=jdbc:mysql://mysql-16e75bd6-mahadevshankar1311-6be4.h.aivencloud.com:16045/defaultdb?sslMode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=10lpa

# --- BAAKI TUMHARI SETTINGS (EKDUM SAFE) ---
spring.application.name=mess-management
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080

# --- Email Configuration (NO CHANGE) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balancedbowlmess@gmail.com
spring.mail.password=dkkq jukb wgpu wysp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true